# Generated by Django 5.2.7 on 2025-10-02 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retirador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('fijo', 'Retirador Fijo'), ('complementario', 'Complementario')], default='fijo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('medico', 'Médico Veterinario'), ('veterinaria', 'Veterinaria'), ('tecnico', 'Técnico Veterinario')], default='medico', max_length=20)),
                ('telefono', models.CharField(help_text='Ej: +56 9 12345678', max_length=20, validators=[django.core.validators.MinLengthValidator(9)])),
                ('email', models.EmailField(help_text='Importante: para enviar resultados', max_length=254, unique=True)),
                ('horarios_atencion', models.TextField(help_text='Ej: Lun-Vie 9:00-18:00')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Valparaíso, Viña del Mar', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_retiro', models.TextField(help_text='Ubicación exacta de las muestras')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('hora_solicitud', models.TimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateField(help_text='Hoy o mañana, según horario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Ej: Tipo de animal (canino, felino), urgencia')),
                ('retirador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retiros.retirador')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retiros.solicitante')),
            ],
        ),
        migrations.AddField(
            model_name='solicitante',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retiros.zona'),
        ),
        migrations.AddField(
            model_name='retirador',
            name='zonas_preferidas',
            field=models.ManyToManyField(help_text='Zonas que suele cubrir', to='retiros.zona'),
        ),
    ]
