# Generated by Django 5.2.7 on 2025-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='direccion_principal',
            field=models.TextField(blank=True, help_text='Dirección fija del solicitante (opcional)'),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='usar_direccion_solicitante',
            field=models.BooleanField(default=True, help_text='¿Usar la dirección principal del solicitante?'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='direccion_retiro',
            field=models.TextField(help_text='Si no usas la del solicitante, pon la ubicación exacta aquí'),
        ),
    ]
