# Generated by Django 5.2.7 on 2025-10-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0002_solicitante_direccion_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='email_desconocido',
            field=models.BooleanField(default=False, help_text='Marque si el email no se conoce aún.'),
        ),
    ]
