# Generated by Django 5.2.7 on 2025-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0003_solicitante_email_desconocido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitante',
            options={'ordering': ['nombre'], 'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='horarios_atencion',
        ),
        migrations.AddField(
            model_name='solicitante',
            name='comentarios_horario_retiro',
            field=models.TextField(blank=True, help_text="Comentarios especiales sobre horarios (ej: 'Desde las 12:00 pm', 'Colación 15-16 hrs')"),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='direccion_desconocida',
            field=models.BooleanField(default=False, help_text='Marque si la dirección no se conoce aún'),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='horario_atencion_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin de atención (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='horario_atencion_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio de atención (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='direccion_principal',
            field=models.TextField(blank=True, help_text='Dirección fija del solicitante (opcional si se marca como desconocida)'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para enviar resultados (opcional si se marca como desconocido)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='email_desconocido',
            field=models.BooleanField(default=False, help_text='Marque si el email no se conoce aún'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del solicitante', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='tipo',
            field=models.CharField(choices=[('medico', 'Médico Veterinario'), ('veterinaria', 'Veterinaria'), ('tecnico', 'Técnico Veterinario'), ('ayudante', 'Ayudante Veterinario'), ('tutor', 'Tutor/Dueño de Mascota')], default='medico', max_length=20),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['nombre'], name='retiros_sol_nombre_1282c8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['tipo'], name='retiros_sol_tipo_a7e42e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['zona'], name='retiros_sol_zona_id_d07bd6_idx'),
        ),
    ]
